#!/usr/bin/env bash
set -ev # halt script on error, show commands being run

JEKYLL_ENV=production bundle exec jekyll build
bundle exec htmlproofer ./_site --assume-extension --check-html --http-status-ignore "999"