#!/usr/bin/env bash
set -ev # halt script on error, show commands being run

openssl aes-256-cbc -K $encrypted_07a038cb33f0_key -iv $encrypted_07a038cb33f0_iv -in private_key.enc -out private_key -d
chmod go-rwx private_key
rsync --exclude .well-known --delete-after -v -r -e "ssh -i private_key" _site/ $REMOTE_USER@assetweb.co.uk:$REMOTE_PATH
